"""常见 OAS 运行日志的展示翻译。

只匹配已确认含义的完整提示或固定格式，未命中的内容原样输出。
页面 ID、点击坐标、设备命令和异常原文不在这里改写。
"""

import logging
import re


PAGE_LOG_LABELS = {
    "page_main": "庭院",
    "page_exploration": "探索",
    "page_team": "组队",
    "page_courtyard_affairs": "庭院事务",
    "page_daily": "每日任务",
    "page_soul_zones": "御魂副本",
    "page_awake_zones": "觉醒副本",
    "page_hero_test": "英杰试炼",
    "page_battle_prepare": "战斗准备",
    "page_battle": "战斗中",
    "page_battle_result": "战斗结算",
    "page_reward": "奖励页面",
    "page_battle_team": "组队房间",
}


def page_log_label(name: str) -> str:
    """同时展示中文页名和原始页面标识，便于读日志和排查。"""
    label = PAGE_LOG_LABELS.get(name)
    return f"{label}（{name}）" if label else name


_MESSAGES = {
    # 任务、登录与调度
    "Start": "启动",
    "App login": "游戏登录",
    "Cancel continue battle": "取消继续战斗",
    "Login to main confirm (shikigami records button appears)": "已确认进入庭院（式神录入口出现）",
    "Login success: shikigami records button appears": "登录成功：式神录入口已出现",
    "The main had already appeared, but shikigami records had not yet appeared": "已进入庭院，但式神录入口尚未出现",
    "Cancel returning to interrupted Chess battle; wait for result flow": "取消返回未完成的弈局战斗，等待结算",
    "Login recovery reached Chess lobby; finish recovery without returning to courtyard": "登录恢复已进入弈局大厅，无需返回庭院",
    "Login recovery detected unfinished Chess result flow": "登录恢复检测到未完成的弈局结算",
    "Close zidu": "关闭 Zidu 弹窗",
    "Soul overflow confirm": "确认御魂溢出提示",
    "Download inbetweening": "处理资源下载提示",
    "Close video": "关闭视频弹窗",
    "Close red close": "点击红色关闭按钮",
    "Close yellow close": "点击黄色关闭按钮",
    "Close bind phone": "关闭绑定手机提示",
    "reject invites": "拒绝邀请",
    "click onmyoji genie": "点击阴阳师精灵",
    "login specific user": "登录指定角色",
    "Appear create account": "出现创建账号页面",
    "Cancel switch from early server to normal server": "取消切换区服",
    "Login failed": "登录失败",
    "Onmyoji server may be under maintenance, or you may lost network connection": "游戏服务器可能正在维护，或网络连接已中断",
    "Log cleanup finished": "过期日志清理完成",
    "Restart": "重启",
    "GotoMain": "返回庭院",
    "Orochi": "八岐大蛇",
    "TrueOrochi": "真八岐大蛇",
    "DailyTrifles": "每日琐事",
    "WeeklyTrifles": "每周琐事",
    "SoulsTidy": "御魂整理",
    "DemonEncounter": "逢魔之时",
    "RealmRaid": "个人突破",
    "RyouToppa": "寮突破",
    "WantedQuests": "悬赏封印",
    "Delegation": "式神委派",
    "Pets": "小猫咪",
    "HeroTest": "英杰试炼",
    "Exploration": "探索",
    "KekkaiUtilize": "结界蹭卡",
    "KekkaiActivation": "结界挂卡",
    "RichMan": "大富翁",
    "Hunt": "狩猎战",
    "Duel": "斗技",
    "BondlingFairyland": "契灵之境",
    "MysteryShop": "神秘商店",
    "TalismanPass": "花合战",
    "MetaDemon": "超鬼王",
    "Hyakkiyakou": "百鬼夜行",
    "CollectiveMissions": "集体任务",
    "Idle wait was interrupted before emulator preheat, reschedule scheduler": "模拟器预热前等待被配置重载中断，重新安排任务",
    "Idle wait was interrupted after emulator preheat, reschedule scheduler": "模拟器预热后等待被配置重载中断，重新安排任务",
    "Idle close_game wait was interrupted by config reload, reschedule scheduler": "关闭游戏后的等待被配置重载中断，重新安排任务",
    "Idle short wait was interrupted by config reload, reschedule scheduler": "短时等待被配置重载中断，重新安排任务",
    "Idle goto_main wait was interrupted by config reload, reschedule scheduler": "返回庭院后的等待被配置重载中断，重新安排任务",
    "Idle stay_there wait was interrupted by config reload, reschedule scheduler": "原地等待被配置重载中断，重新安排任务",
    "App stop": "关闭游戏",
    "App start": "启动游戏",
    "App restart": "重启游戏",
    # 战斗、阵容和加成
    "Green is enable": "已启用绿标",
    "Green left 1": "绿标位置：左侧第 1 位",
    "Green left 2": "绿标位置：左侧第 2 位",
    "Green left 3": "绿标位置：左侧第 3 位",
    "Green left 4": "绿标位置：左侧第 4 位",
    "Green left 5": "绿标位置：左侧第 5 位",
    "Green main": "绿标位置：主目标",
    "Green mark name is empty": "绿标目标名称为空",
    "Preset is disable": "未启用预设队伍切换",
    "Preset is enable": "已启用预设队伍切换",
    "Switch preset timeout, use current team": "切换预设队伍超时，继续使用当前阵容",
    "Click preset button": "点击预设队伍按钮",
    "Select preset group": "选择预设分组",
    "Select preset team": "选择预设队伍",
    "Click preset ensure success": "预设队伍已确认",
    "Lock team": "锁定队伍",
    "Unlock team": "解锁队伍",
    "Cannot open buff, exit": "无法打开加成界面，跳过加成设置",
    "Open buff success": "加成设置完成",
    "Battle page recognized but no general battle handler is available": "已识别战斗页面，但没有可用的战斗处理程序",
    "Battle prepare": "战斗准备",
    "Enter battle": "进入战斗",
    "Enter AP battle": "进入体力挑战",
    "Check tickets": "检查挑战券",
    "Open buff": "打开加成界面",
    "Close buff": "关闭加成界面",
    "Gold 50 buff": "金币 50% 加成",
    "No gold 50 buff": "未找到金币 50% 加成",
    "Start open gold50 buff": "开启金币 50% 加成",
    "Start close gold50 buff": "关闭金币 50% 加成",
    "Gold 100 buff": "金币 100% 加成",
    "No gold 100 buff": "未找到金币 100% 加成",
    "Start open gold100 buff": "开启金币 100% 加成",
    "Start close gold100 buff": "关闭金币 100% 加成",
    "Exp 50 buff": "经验 50% 加成",
    "No exp 50 buff": "未找到经验 50% 加成",
    "Start open exp50 buff": "开启经验 50% 加成",
    "Start close exp50 buff": "关闭经验 50% 加成",
    "Exp 100 buff": "经验 100% 加成",
    "No exp 100 buff": "未找到经验 100% 加成",
    "Start open exp100 buff": "开启经验 100% 加成",
    "Start close exp100 buff": "关闭经验 100% 加成",
    "Awake buff": "觉醒加成",
    "No awake buff": "未找到觉醒加成",
    "Start open awake buff": "开启觉醒加成",
    "Start close awake buff": "关闭觉醒加成",
    "Soul buff": "御魂加成",
    "No soul buff": "未找到御魂加成",
    "Start open soul buff": "开启御魂加成",
    "Start close soul buff": "关闭御魂加成",
    # 组队与邀请
    "Invite friends": "邀请好友",
    "Not enter invite page": "未进入组队邀请页面",
    "Wait timeout": "等待超时",
    "Timeout, now is no room": "等待超时，当前已不在房间",
    "Invitation is triggered every 20s": "每 20 秒重新发出邀请",
    "Wait for 30s and invite again": "等待 30 秒后再次邀请",
    "Start challenge and this room can only invite one friend": "队友已到齐，开始挑战（该房间只能邀请 1 人）",
    "Start challenge and user only invite one friend": "已邀请 1 位队友，开始挑战",
    "Start challenge and user invite two friends": "已邀请 2 位队友，开始挑战",
    "Start challenge and this is lock sea": "永生之海队友已到齐，开始挑战",
    "Start challenge and this is bondling fairyland": "契灵之境队友已到齐，开始挑战",
    "No friend to invite": "没有需要邀请的好友",
    "Ensure enter invite page": "确认已进入组队邀请页面",
    "Exit room": "退出组队房间",
    "Room can only be one people, but invite two people": "房间只能邀请 1 人，当前却配置了 2 人",
    "Current page no exact friend": "当前页面未找到完全匹配的好友",
    "Click add to invite friend": "点击添加好友入口",
    "Cannot invite friend, maybe already existing": "无法邀请好友，可能对方已在房间内",
    "Find recent friend": "查找最近联系人",
    "No recent friend": "最近联系人中没有可邀请的好友",
    "Click invite ensure": "确认邀请",
    "No appear invite ensure while invite friend": "邀请好友时未出现确认按钮",
    "Cannot find friend": "未找到好友",
    "Invite again": "再次邀请",
    "Click default invite": "勾选默认邀请",
    "Click no default invite": "取消默认邀请",
    "Click accept": "接受邀请",
    "Now find friend in ”最近“": "在最近联系人中查找好友",
    "No appear invite ensure while invite friend": "邀请好友时未出现确认按钮",
    # 常见任务
    "Unknown user status": "未知的用户身份配置",
    "Start run leader": "以队长身份开始任务",
    "Start run member": "以队员身份开始任务",
    "Start run alone": "以单人模式开始任务",
    "Start run wild": "以野队模式开始任务",
    "Create team": "创建队伍",
    "Wait for starting": "等待开始挑战",
    "Invitation appearing": "检测到好友邀请",
    "Accept friend invitation": "接受好友邀请",
    "Reject friend invitation": "拒绝好友邀请",
    "Only accept jade invitation": "只接受勾玉协作邀请",
    "Accept jade and food invitation": "接受勾玉及宠物粮食协作邀请",
    "Ignore friend invitation": "忽略好友邀请",
    "Deal with invitation done": "好友邀请已处理",
    "Get reward success": "奖励领取成功",
    "Get reward timeout": "领取奖励超时",
    "Switch soul by name": "按名称切换御魂",
    "Start switch soul": "开始切换御魂",
    "Quick loadout": "快速预设",
    "True Orochi Battle": "真八岐大蛇战斗",
    "Find true orochi after orochi battle, set TrueOrochi task to run now": "发现真八岐大蛇，已安排立即执行真蛇任务",
    "Start wanted quests": "开始悬赏封印",
    "Start activation": "开始结界挂卡",
    "Start boss battle": "开始首领战斗",
    "Check fatigue": "检查疲劳值",
    "Summon boss": "召唤首领",
    "Search boss": "查找首领",
    "Harvest soul": "领取御魂",
    "Peacock Kingdom": "孔雀之国",
    "Moon Sea": "月之海",
    "Switch onmyoji": "切换阴阳师",
    "Start run catch": "开始捕捉",
    "Run Orochi": "开始八岐大蛇",
    "Feed": "喂养宠物",
    "Duel battle": "斗技战斗",
    "duel battle matching": "斗技匹配中",
    "duel battle preparing": "斗技准备中",
    "duel battle waiting": "等待斗技开始",
    "Start utilize": "开始结界蹭卡",
    "Start Hyakkiyakou": "开始百鬼夜行",
    "Start Kitty Shop": "开始猫咪商店",
    "Kitty Shop": "猫咪商店",
    "Start Shrine": "进入神龛",
    "Start guild": "进入阴阳寮",
    "Mall": "商店",
    "Quiz": "答题",
    "Touch fish start": "开始摸鱼",
    "Touch fish finished": "摸鱼完成",
    "Share collect": "领取分享奖励",
    "Share area boss": "分享地域鬼王",
    "Share secret": "分享秘闻",
    "Broken amulet": "破碎符咒",
    "Switch to 50 amulet": "切换为每次 50 张破碎符咒",
    "Switch to 10 amulet": "切换为每次 10 张破碎符咒",
    "Detect device": "检测设备",
    "Detect package": "检测游戏应用",
    "Wait too long": "等待时间过长",
    "Disable stuck detection": "关闭卡住检测",
    "Wait game start ready timeout, continue with login flow": "等待游戏启动超时，继续登录流程",
    "Received orientated screenshot, handling": "收到方向不符的截图，正在调整",
    "Unable to handle orientated screenshot, continue for now": "无法调整截图方向，继续尝试运行",
    "Received orientated screenshot, game not running": "截图方向异常，游戏可能尚未运行",
    "Uninstall minicap and retry": "请卸载 minicap 后重试",
    "If you are using MuMu X, please upgrade to version >= 12.1.5.0": "如果使用 MuMu X，请升级到 12.1.5.0 或更高版本",
    "Unknown ui page or navigation stalled": "无法识别当前页面，或页面切换停滞",
    "Try switch to a supported page": "尝试切换到可识别的页面",
    # 设备与连接
    "Restart adb": "重启 ADB 连接服务",
    "Install uiautomator2": "安装 uiautomator2",
    "Removing minicap": "移除 minicap",
    "Restart ATX": "重启 ATX 服务",
    "No available devices": "没有可用设备",
    "Get package list": "获取设备上的应用列表",
    "No available packages": "设备上没有可用的游戏应用",
    "Server changed, release resources": "设备连接已变化，释放旧连接资源",
    "No such device exists, please restart the emulator or set a correct serial": "找不到设备，请重启模拟器或检查设备序列号",
    "No `netcat` command available, please use screenshot methods without `_nc` suffix": "未找到 netcat，请改用不带 _nc 后缀的截图方式",
    "Device": "设备",
    "Find emulator instance": "查找模拟器实例",
    "Emulator instance": "模拟器实例",
    "Emulator start": "启动模拟器",
    "Emulator stop": "关闭模拟器",
    "Scrcpy init": "初始化 Scrcpy",
    "Scrcpy server start": "启动 Scrcpy 服务",
    "Scrcpy server stop": "关闭 Scrcpy 服务",
    "MiniTouch init": "初始化 MiniTouch",
    "DroidCast init": "初始化 DroidCast",
    "Here are the devices detected but unavailable": "检测到以下不可用设备",
    "Auto device detection found only one device, using it": "自动检测到唯一的设备，使用该设备",
    "Auto package detection found only one package, using it": "自动检测到唯一的游戏应用，使用该应用",
}

_EXACT = {original.casefold(): translated for original, translated in _MESSAGES.items()}

_PATTERNS = (
    (re.compile(r"^Need invite friend list: (.+)$"), "待邀请好友：{}"),
    (re.compile(r"^Room type: (.+)$"), "房间类型：{}"),
    (re.compile(r"^Friend class: (.+)$"), "好友分类：{}"),
    (re.compile(r"^Now find friend in (.+)$"), "在 {} 中查找好友"),
    (re.compile(r"^Exact match friend \"(.+)\" in (.+) at (.+)$"), "找到好友“{}”，匹配规则 {}，位置 {}"),
    (re.compile(r"^Find friend \"(.+)\" but failed to select$"), "找到好友“{}”，但未能选中"),
    (re.compile(r"^Green name success, text: (.+)$"), "已找到绿标目标：{}"),
    (re.compile(r"^Green name failed, best text: (.+)$"), "未找到绿标目标，最接近的文字：{}"),
    (re.compile(r"^Open buff (.+)$"), "设置加成：{}"),
    (re.compile(r"^No (.+) buff$"), "未找到 {} 加成"),
    (re.compile(r"^Wait until appear (.+) timeout$"), "等待 {} 出现超时"),
    (re.compile(r"^Wait until (.+) position stable$"), "等待 {} 位置稳定"),
    (re.compile(r"^(.+) position has stabilized$"), "{} 位置已稳定"),
    (re.compile(r"^Wait until pos stable\((.+)\) timeout$"), "等待 {} 位置稳定超时"),
    (re.compile(r"^Wait_until_stable\((.+)\) timeout$"), "等待 {} 稳定超时"),
    (re.compile(r"^Wait_animate_stable\((.+)\) timeout$"), "等待 {} 动画稳定超时"),
    (re.compile(r"^Check lantern (.+)$"), "检查第 {} 个灯笼"),
    (re.compile(r"^Answer (.+)$"), "回答第 {} 题"),
    (re.compile(r"^Waiting for (.+)$"), "正在等待：{}"),
    (re.compile(r"^History click: (.+)$"), "近期点击记录：{}"),
    (re.compile(r"^Too many click for a button: (.+)$"), "同一按钮点击过多：{}"),
    (re.compile(r"^Too many click between 2 buttons: (.+)$"), "两个按钮之间反复点击：{}"),
    (re.compile(r"^Game start ready, frame color: (.+)$"), "游戏启动画面已就绪，画面颜色：{}"),
    (re.compile(r"^Wait game start ready: screenshot probe failed: (.+)$"), "等待游戏启动时截图检查失败：{}"),
    (re.compile(r"^Push notify: (.+)$"), "发送通知：{}"),
    (re.compile(r"^Save image: (.+)$"), "保存图片：{}"),
    (re.compile(r"^Invalid priority: (.+)$"), "无效的任务优先级：{}"),
    (re.compile(r"^No task named (.+)$"), "找不到名为 {} 的任务"),
    (re.compile(r"^No scheduler in (.+)$"), "任务 {} 没有调度配置"),
    (re.compile(r"^Server update wait during (.+) was interrupted by config reload, reschedule scheduler$"), "服务器更新等待在 {} 阶段被配置重载中断，重新安排任务"),
    (re.compile(r"^Probe target emulator failed: (.+)$"), "检查目标模拟器失败：{}"),
    (re.compile(r"^Invalid Optimization_WhenTaskQueueEmpty: (.+), fallback to stay_there$"), "空任务队列等待方式 {} 无效，改为原地等待"),
    (re.compile(r"^Screenshot interval set to ([\d.]+)s$"), "截图间隔已设为 {} 秒"),
    (re.compile(r"^Screenshot method (.+)$"), "截图方式：{}"),
    (re.compile(r"^Unknown screenshot interval: (.+)$"), "未知的截图间隔：{}"),
    (re.compile(r"^Received pure black screenshots from emulator, color: (.+)$"), "模拟器返回纯黑截图，颜色值：{}"),
    (re.compile(r"^Optimization\.ScreenshotInterval (.+) is revised to (.+)$"), "普通截图间隔由 {} 调整为 {}"),
    (re.compile(r"^Optimization\.CombatScreenshotInterval (.+) is revised to (.+)$"), "战斗截图间隔由 {} 调整为 {}"),
    (re.compile(r"^Page detect miss\[(.+)\]: scoped=(.+)$"), "页面识别未命中（{}），检查范围：{}"),
    (re.compile(r"^Current page: (.+)$"), "当前页面：{}"),
    (re.compile(r"^Target page: (.+)$"), "目标页面：{}"),
    (re.compile(r"^Allowed categories: (.+)$"), "允许的页面分类：{}"),
    (re.compile(r"^Current task category: (.+)$"), "当前任务分类：{}"),
    (re.compile(r"^Current page checks: (.+)$"), "当前页面识别结果：{}"),
    (re.compile(r"^Last path signature: (.+)$"), "上次切换路径：{}"),
    (re.compile(r"^Last repeated-failure close result: (.+)$"), "重复失败后的关闭结果：{}"),
    (re.compile(r"^Edge penalties: (.+)$"), "页面切换失败惩罚值：{}"),
    (re.compile(r"^Unknown close history: (.+)$"), "未知页面的关闭记录：{}"),
    (re.compile(r"^Transition failed before leaving (.+): (.+), penalty=(.+)$"), "离开 {} 时页面切换失败：{}，惩罚值 {}"),
    (re.compile(r"^Transition cannot reach (.+): (.+), penalty=(.+)$"), "无法到达 {}：{}，惩罚值 {}"),
    (re.compile(r"^Transition (.+) repeated failure close result: (.+)$"), "页面切换 {} 连续失败，关闭弹窗结果：{}"),
    (re.compile(r"^Execute: (.+)$"), "执行命令：{}"),
    (re.compile(r"^CPU ABI invalid: (.+)$"), "设备 CPU 架构无效：{}"),
    (re.compile(r"^SDK version invalid: (.+)$"), "设备 SDK 版本无效：{}"),
    (re.compile(r"^Connecting to local emulator, using host (.+)$"), "正在连接本地模拟器，主机：{}"),
    (re.compile(r"^Connecting to BlueStacks hyper-v, using host (.+)$"), "正在连接 BlueStacks Hyper-V，主机：{}"),
    (re.compile(r"^Connecting to local network device, using host (.+)$"), "正在连接局域网设备，主机：{}"),
    (re.compile(r"^Connecting to unknown device, using host (.+)$"), "正在连接设备，主机：{}"),
    (re.compile(r"^Current hosts: (.+)$"), "当前可用主机：{}"),
    (re.compile(r"^Reuse forward: (.+)$"), "复用端口转发：{}"),
    (re.compile(r"^Remove redundant forward: (.+)$"), "移除多余的端口转发：{}"),
    (re.compile(r"^Create forward: (.+)$"), "创建端口转发：{}"),
    (re.compile(r"^Reuse reverse: (.+)$"), "复用反向端口转发：{}"),
    (re.compile(r"^Create reverse: (.+)$"), "创建反向端口转发：{}"),
    (re.compile(r"^ADB connect (.+) failed: (.+)$"), "ADB 连接 {} 失败：{}"),
    (re.compile(r"^Device (.+) is offline, disconnect it before connecting$"), "设备 {} 已离线，请断开后重新连接"),
    (re.compile(r"^Device (.+) is unauthorized, please accept ADB debugging on your device$"), "设备 {} 未授权，请在设备上允许 ADB 调试"),
    (re.compile(r"^Failed to connect (.+) after 3 trial, detect device status$"), "连接 {} 连续失败 3 次，正在检查设备状态"),
    (re.compile(r"^Invalid device orientation: (.+), assume it is normal$"), "设备方向值无效：{}，按正常方向处理"),
    (re.compile(r"^Unable to get device orientation, assume it is normal$"), "无法读取设备方向，按正常方向处理"),
    (re.compile(r"^No available packages on device \"(.+)\"$"), "设备“{}”上没有可用的游戏应用"),
    (re.compile(r"^Here are the available packages in device \"(.+)\", (.+)$"), "设备“{}”上的可用应用：{}"),
)


def localize_log_text(message: str) -> str:
    """只翻译已知提示；未知消息原样返回。"""
    if not isinstance(message, str):
        return message
    exact = _EXACT.get(message.casefold())
    if exact is not None:
        return exact
    if message.casefold().startswith("ui goto "):
        return f"前往页面：{page_log_label(message[8:])}"
    for pattern, template in _PATTERNS:
        match = pattern.fullmatch(message)
        if match:
            return template.format(*match.groups())
    return message


class LocalizedLogFilter(logging.Filter):
    """只改写展示文字，保留日志级别、源码位置和异常信息。"""

    def filter(self, record: logging.LogRecord) -> bool:
        original = record.getMessage()
        translated = localize_log_text(original)
        if translated != original:
            record.msg = translated
            record.args = ()
        return True
